/**
 * Activity-log PDF renderer.
 *
 * Extracted from the body of POST /api/admin/activity-log/pdf
 * (routes/admin.ts) so the document can be rendered — and therefore
 * asserted on — without an Express request. The route keeps auth, params,
 * the fetch and the response headers; everything below is layout.
 *
 * The extraction itself was a pure move, proven byte-identical against
 * 00e2298 at 65c12d7. Everything since is a deliberate fix with a failing
 * assertion recorded in its commit — see _activityLog.test.ts, which reads
 * the rendered PDF through poppler rather than reading this file.
 *
 * Media policy is unchanged: counts only, no embedded images and no
 * filenames, so a 5-photo incident weighs the same as a bare ping.
 */
import PDFDocument from 'pdfkit';
import {
  NAVY, WHITE, BLUE, RED, AMBER, GRAY1, GRAY2, TEXT, MUTED,
  PAGE_W, ML, MR, CW,
  drawFooter, badge, stampPages,
  CONTENT_TOP, CONTENT_BOTTOM,
} from './theme';
import { ACTIVITY_PDF_ROW_CAP, type ActivityRow, type StatusKind } from '../../routes/activityLog';

/**
 * The zone every date in this document is rendered in.
 *
 * Hardcoded, matching the three Intl formatters below that already were —
 * all 23 production sites read `America/Los_Angeles`. It is named rather
 * than repeated so that the day a site exists in another zone, `grep SITE_TZ`
 * finds every place that has to change. Tracked in OPEN-ITEMS.
 */
const SITE_TZ = 'America/Los_Angeles';

/**
 * Badge colour per status kind.
 *
 * Record<StatusKind, ...> ON PURPOSE. These were Record<string, string>, so
 * the four kinds below were simply absent and tsc had nothing to say about
 * it: the renderer fell through to `?? MUTED`, and MISSED CLOCK IN — the
 * most serious row this document can carry — printed in the same grey as a
 * completed task while MISSED PING printed red. Widening the key type back
 * to string reopens that silently, which is the point of narrowing it.
 *
 * Colours mirror ActivityLogTable's pills so the two surfaces agree: an
 * unmet obligation is RED, a satisfied-but-late one AMBER, and anything
 * routine NAVY.
 */
export const STATUS_COLOR: Record<StatusKind, string> = {
  on_time:                   NAVY,
  late:                      AMBER,
  missed:                    RED,
  // Missed then answered: RED. The window WAS missed, and a document a
  // client reads must not soften that because the guard caught up.
  missed_answered_late:      RED,
  activity_report:           BLUE,
  incident_report:           RED,
  maintenance_report:        AMBER,
  checkpoint_round_complete: NAVY,
  checkpoint_round_partial:  AMBER,
  task_completed:            NAVY,
  // The four that were missing. RED on all three "missed" kinds, matching
  // `missed` above — an obligation nobody met reads the same whichever
  // obligation it was.
  clocked_in_on_time:        NAVY,
  clocked_in_late:           RED,
  missed_clock_in:           RED,
  missed_report:             RED,
};
export const STATUS_LABEL: Record<StatusKind, string> = {
  on_time:                   'PING',
  late:                      'LATE PING',
  missed:                    'MISSED PING',
  // Row's `status` already reads "Missed — answered N minutes late";
  // the badge is the short form.
  missed_answered_late:      'MISSED / ANSWERED LATE',
  activity_report:           'ACTIVITY',
  incident_report:           'INCIDENT',
  maintenance_report:        'MAINTENANCE',
  // Deliberately no "x of y" here. This document is generated by an admin
  // but handed to a client, and the counts are a comparison against the
  // current checkpoint roster, which can change retroactively. Complete
  // vs partial is a standalone fact and is safe to print.
  checkpoint_round_complete: 'ROUND COMPLETE',
  checkpoint_round_partial:  'ROUND PARTIAL',
  task_completed:            'TASK COMPLETED',
  // BOTH clock-in kinds carry status 'Clocked In' from the builder, so the
  // old `?? r.status.toUpperCase()` fallback rendered them as the same
  // "CLOCKED IN" badge in the same grey. The PDF could not tell an admin
  // which of the two it was looking at; the web has always shown
  // "Clocked In at 12:18 (+18m late)" in red. The exact +Nm figure lands on
  // the detail line in the next commit — this pair only has to be distinct.
  clocked_in_on_time:        'CLOCKED IN',
  clocked_in_late:           'CLOCKED IN LATE',
  missed_clock_in:           'MISSED CLOCK IN',
  missed_report:             'MISSED REPORT',
};


/**
 * Kinds whose row is sorted — and therefore printed — at a SCHEDULED instant
 * rather than an observed one.
 *
 * All four carry that instant in event_time already: the window start for a
 * missed or merged ping, the hour start for a missed report, scheduled_start
 * for a missed clock-in. The data was never absent; the renderer read
 * log_time, which is null on three of them and MISLEADING on the fourth.
 */
const SCHEDULED_TIME_KINDS: ReadonlySet<StatusKind> = new Set<StatusKind>([
  'missed', 'missed_report', 'missed_clock_in', 'missed_answered_late',
]);

/**
 * The fact the badge's short form drops, or null when it drops nothing.
 *
 * WHICH KINDS, AND WHY NOT on_time. Every ping row used to get a qualifier,
 * which cost a line each and took a full export from 90 pages to 122 (+36%).
 * A routine on-time ping is the overwhelming majority of rows and the least
 * interesting thing in the document: its badge, its time and its position in
 * the day already say everything, and "(3 minutes)" is offset-into-window
 * detail nobody reads a 90-page PDF for. It is one line again.
 *
 * The kinds that keep a qualifier are the ones whose badge is lossy — an
 * exception the reader is meant to act on:
 *   late                  LATE PING drops HOW late
 *   missed_answered_late  drops both WHEN it was answered and by how much
 *   clocked_in_late       builder gives BOTH clock-in kinds the identical
 *                         status 'Clocked In', so the delta is computed
 *   missed / missed_report / missed_clock_in  — see the guard below
 *
 * THE GUARD. For those last three the builder's status is 'Missed Ping',
 * 'Missed Report' and 'Missed Clock In' — the badge label verbatim. Printing
 * it would add a line that restates the badge and costs 8pt a row, so a
 * qualifier that only echoes its own badge is dropped. The rule is
 * mechanical rather than a hand-maintained list: the day one of those
 * statuses grows a detail (a window name, a reason), it starts printing on
 * its own with nothing here to change.
 *
 * `r.status` is rendered VERBATIM and never parsed — the same rule the
 * mobile client follows for error copy.
 */
function buildQualifier(r: ActivityRow, label: string): string | null {
  let q: string | null = null;

  if (r.status_kind === 'clocked_in_late' && r.log_time && r.scheduled_start) {
    const late = Math.max(0, Math.floor(
      (Date.parse(r.log_time) - Date.parse(r.scheduled_start)) / 60_000));
    q = `Clocked In at ${TIME_LABEL.format(new Date(r.log_time))} (+${late}m late)`;
  } else if (QUALIFIED_KINDS.has(r.status_kind)) {
    q = r.status;
  }

  // Drop a qualifier that only restates its badge.
  if (q && q.trim().toUpperCase() === label.trim().toUpperCase()) return null;
  return q;
}

/** Kinds whose badge is a lossy short form of the server's own status text. */
const QUALIFIED_KINDS: ReadonlySet<StatusKind> = new Set<StatusKind>([
  'late', 'missed', 'missed_answered_late', 'missed_report', 'missed_clock_in',
]);

/** Module-scope twin of the in-function TIME_FMT, for buildQualifier. */
const TIME_LABEL = new Intl.DateTimeFormat('en-GB', {
  hour: '2-digit', minute: '2-digit', timeZone: SITE_TZ,
});

export interface ActivityPdfMeta {
  /** Site name, or 'All sites' when the export is not site-filtered. */
  siteLabel:   string;
  /** Range as the caller received it on the wire. */
  fromIso:     string;
  toIso:       string;
  /**
   * Set when the export is scoped to ONE shift_session. Absent otherwise.
   * Resolved by the route, because the renderer does not touch the database.
   *
   * THIS IS THE WHOLE OF D1. A 19-event export scoped to a single session
   * carried a cover reading "Guard: All guards" and "MISSED 0". Both were
   * true of the session and neither was true of the day: two guards worked
   * that site on 2026-09-21, and the other one missed eleven windows. The
   * filter was never broken — the header simply never mentioned it, so a
   * reader had no way to know the document was a slice.
   */
  shift?: {
    guardName:   string;
    siteName:    string;
    /** ISO instant; rendered in SITE_TZ, never the server's zone. */
    clockedInAt: string;
  };
}

/**
 * Render the feed to a PDF buffer.
 *
 * `rows` is sorted in place (newest first) and capped at
 * ACTIVITY_PDF_ROW_CAP; the TOTAL EVENTS tile reports the uncapped length,
 * which is why the full array is taken rather than a pre-sliced one.
 */
export function renderActivityLogPdf(
  rows: ActivityRow[],
  meta: ActivityPdfMeta,
): Promise<Buffer> {
  const { siteLabel, fromIso, toIso, shift } = meta;
  // Newest first (matches on-screen order)
  rows.sort((a, b) => Date.parse(b.event_time) - Date.parse(a.event_time));
  const truncated = rows.length > ACTIVITY_PDF_ROW_CAP;
  const eventRows = rows.slice(0, ACTIVITY_PDF_ROW_CAP);
  // En dash, not an arrow: WinAnsi has no → and PDFKit's built-in Helvetica
  // rendered it as "!'" on every page of this PDF.
  //
  // THE ZONE IS NOT OPTIONAL. Without it these two calls format in the
  // PROCESS's zone, and Railway sets no TZ, so the API runs in UTC. The web
  // sends an INCLUSIVE end-of-local-day bound — localDayEnd() parses
  // "<date>T23:59:59.999" with no suffix, so a PT browser puts
  // 2026-09-23T06:59:59.999Z on the wire for a picker end of 2026-09-22 —
  // and 06:59Z is the next day in UTC. The header therefore printed 23/09
  // against a filename, built from the same click, reading 09-22.
  //
  // Only the END was ever visibly wrong, which is why this went unnoticed:
  // a start-of-day PT bound is 07:00Z on the SAME date, so the start agreed
  // by luck. It is not an exclusive-end bug — the bound really is inclusive.
  //
  // Every sibling formatter in this file already passes the zone (DAY_KEY,
  // DAY_HEADER, TIME_FMT, and the Generated line below). This call was the
  // only one that did not, so it was an omission, not a choice.
  const periodStr =
    `${new Date(fromIso).toLocaleDateString('en-GB', { timeZone: SITE_TZ })}` +
    ` – ${new Date(toIso).toLocaleDateString('en-GB', { timeZone: SITE_TZ })}`;

  // Group by Pacific-time day for the on-page sections.
  const DAY_KEY = new Intl.DateTimeFormat('en-CA', {
    year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'America/Los_Angeles',
  });
  const DAY_HEADER = new Intl.DateTimeFormat('en-GB', {
    weekday: 'long', day: '2-digit', month: 'short', year: 'numeric', timeZone: 'America/Los_Angeles',
  });
  const TIME_FMT = new Intl.DateTimeFormat('en-GB', {
    hour: '2-digit', minute: '2-digit', timeZone: 'America/Los_Angeles',
  });
  // Clock-in on the Shift line: dated as well as timed, because a shift
  // filter is the one case where the document may cover a single day that
  // is not obvious from the period.
  const SHIFT_CLOCK_FMT = new Intl.DateTimeFormat('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZone: SITE_TZ,
  });

  const byDay = new Map<string, ActivityRow[]>();
  for (const r of eventRows) {
    const key = DAY_KEY.format(new Date(r.event_time));
    if (!byDay.has(key)) byDay.set(key, []);
    byDay.get(key)!.push(r);
  }
  const dayKeys = Array.from(byDay.keys()).sort().reverse();
  for (const key of dayKeys) byDay.get(key)!.sort((a, b) => Date.parse(a.event_time) - Date.parse(b.event_time));

  // bufferPages holds the PAGE OBJECTS open so the real count is known
  // before the chrome is stamped. It is not the same thing as buffering
  // the output, which the Buffer return already does.
  const doc = new PDFDocument({ margin: 0, size: 'A4', autoFirstPage: true, bufferPages: true });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('data',  (c: Buffer) => chunks.push(c));
    doc.on('end',   () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  // ── Page 1 — Cover / filter summary ─────────────────────────────────────
  // No page number is drawn here. `bufferPages` holds the page objects open
  // so stampPages() can write the chrome at the end, once the real count is
  // known — the guardHours.ts pattern.
  //
  // What this replaces: `1 + max(1, ceil(rows / 20))`. Two errors compounding
  // in the same direction. The `1 +` assumed a standalone cover, but the
  // timeline starts on the SAME page as the cover; and 20 rows/page badly
  // under-counted real density (823 production rows occupied 28 pages, ~29
  // each). On the PDF that prompted this work it declared "1 / 43" across
  // 28 pages. Its floor was also 2, so a one-page export could not ever be
  // labelled correctly no matter how the constant was tuned.
  let y = CONTENT_TOP;

  doc.fontSize(22).fillColor(TEXT).font('Helvetica-Bold').text('Activity Logs', ML, y);
  y += 30;

  doc.fontSize(10).fillColor(MUTED).font('Helvetica')
     .text(`Period      ${periodStr}`, ML, y);
  y += 15;
  doc.text(`Site        ${siteLabel}`, ML, y);
  y += 15;
  // No Guard line. This route no longer accepts guard_id — the web never
  // sent it (ActivityLogTable.tsx:611-612 sends site_id and session_id and
  // nothing else), so the line could only ever read "All guards", and a
  // constant that looks like a filter summary is worse than no line: on the
  // session-scoped export it actively asserted the opposite of the truth.
  //
  // The guard a reader actually wants is named on the Shift line below,
  // where it means something.
  if (shift) {
    doc.text(
      `Shift       ${shift.guardName} \u00B7 ${shift.siteName} \u00B7 ` +
      `${SHIFT_CLOCK_FMT.format(new Date(shift.clockedInAt))} PT`,
      ML, y,
    );
    y += 15;
  }
  doc.text(`Generated   ${new Date().toLocaleString('en-GB', { timeZone: 'America/Los_Angeles' })} PT`, ML, y);
  y += 22;

  doc.moveTo(ML, y).lineTo(MR, y).strokeColor(GRAY2).lineWidth(0.5).stroke();
  y += 18;

  // Summary tile row
  const totalRows        = rows.length;
  // A window that was missed counts as missed even once it was answered
  // late — that is the whole point of keeping the resolved row. It is
  // deliberately NOT also added to pingCount: the merged row is one row,
  // so counting it in both tiles would stop the cover reconciling with
  // the body. Row totals are unchanged by the merge (a resolved window
  // used to emit one ping row; it now emits one missed_answered_late row).
  const missedCount      = eventRows.filter(
    (r) => r.status_kind === 'missed' || r.status_kind === 'missed_answered_late',
  ).length;
  const incidentCount    = eventRows.filter((r) => r.status_kind === 'incident_report').length;
  const activityCount    = eventRows.filter((r) => r.status_kind === 'activity_report').length;
  const maintenanceCount = eventRows.filter((r) => r.status_kind === 'maintenance_report').length;
  const pingCount        = eventRows.filter((r) => r.status_kind === 'on_time' || r.status_kind === 'late').length;
  // Patrol rounds are counted so the cover reconciles with the body. Without
  // this the tiles would report fewer events than the pages actually list.
  //
  // One tile, not two: the tile row divides CW evenly, so an eighth tile
  // narrows every box enough that TOTAL EVENTS / MAINTENANCE wrap onto a
  // second line and overflow their fixed 56pt height. Complete-vs-partial is
  // already legible per row via the ROUND COMPLETE / ROUND PARTIAL badges;
  // splitting it out on the cover is not worth breaking the existing labels.
  const roundCount       = eventRows.filter((r) => r.kind === 'checkpoint_round').length;

  const stats = [
    { label: 'TOTAL EVENTS', value: totalRows,        color: TEXT  },
    { label: 'PINGS',        value: pingCount,        color: NAVY  },
    { label: 'MISSED',       value: missedCount,      color: RED   },
    { label: 'ROUNDS',       value: roundCount,       color: NAVY  },
    { label: 'ACTIVITY',     value: activityCount,    color: BLUE  },
    { label: 'INCIDENT',     value: incidentCount,    color: RED   },
    { label: 'MAINTENANCE',  value: maintenanceCount, color: AMBER },
  ];
  const statW = CW / stats.length;
  for (let i = 0; i < stats.length; i++) {
    const sx = ML + i * statW;
    doc.rect(sx + 2, y, statW - 4, 56).fill(GRAY1).stroke();
    doc.rect(sx + 2, y, 3, 56).fill(stats[i].color);
    doc.fontSize(22).fillColor(stats[i].color).font('Helvetica-Bold')
       .text(String(stats[i].value), sx + 10, y + 8, { width: statW - 16, lineBreak: false });
    doc.fontSize(7).fillColor(MUTED).font('Helvetica')
       .text(stats[i].label, sx + 10, y + 40, { width: statW - 16 });
  }
  y += 70;

  if (truncated) {
    doc.rect(ML, y, CW, 18).fill('#FEF3C7');
    doc.fontSize(8).fillColor('#92400E').font('Helvetica-Bold')
       .text(`Truncated: ${totalRows} total events, showing first ${ACTIVITY_PDF_ROW_CAP}. Narrow the filter to see more.`,
             ML + 8, y + 5, { width: CW - 16, lineBreak: false });
    y += 24;
  }

  doc.moveTo(ML, y).lineTo(MR, y).strokeColor(GRAY2).lineWidth(0.5).stroke();
  y += 14;

  // ── Timeline: per-day sections ──────────────────────────────────────────
  const COL_TIME_X   = ML + 8;
  const COL_STATUS_X = ML + 60;
  const COL_GUARD_X  = ML + 170;
  const COL_SITE_X   = ML + 300;
  const COL_DESC_X   = ML + 8;
  const ROW_H        = 18;
  const ROW_DESC_H   = 26;

  function ensureRoom(needed: number) {
    // CONTENT_BOTTOM (PAGE_H - 46), not the PAGE_H - 40 this used before.
    // theme.ts stamps the chrome after layout and states the contract that
    // makes that safe: body content stays inside CONTENT_TOP..CONTENT_BOTTOM.
    // The old bound let a 26pt row end 10pt above the footer's fill — no
    // overlap, but outside the contract being relied on. Costs at most one
    // row per page.
    if (y + needed > CONTENT_BOTTOM) {
      doc.addPage();
      y = CONTENT_TOP;
    }
  }

  if (eventRows.length === 0) {
    doc.fontSize(12).fillColor(MUTED).font('Helvetica')
       .text('No events in this range.', ML, y, { width: CW, align: 'center' });
  }

  for (const key of dayKeys) {
    ensureRoom(30);
    const dayRows = byDay.get(key)!;
    const dayDate = new Date(dayRows[0].event_time);

    // Day header bar
    doc.rect(ML, y, CW, 20).fill(NAVY);
    doc.fontSize(9).fillColor(WHITE).font('Helvetica-Bold')
       .text(DAY_HEADER.format(dayDate).toUpperCase(), ML + 8, y + 6, { lineBreak: false });
    doc.fontSize(8).fillColor('#94A3B8').font('Helvetica')
       .text(`${dayRows.length} event${dayRows.length !== 1 ? 's' : ''}`,
             0, y + 6, { align: 'right', width: PAGE_W - ML });
    y += 26;

    for (const r of dayRows) {
      // TIME COLUMN. Rows are SORTED on event_time; this column used to print
      // log_time, so for a merged missed/answered row the two disagreed and
      // the row landed nowhere near the time it displayed. On 2026-09-08 that
      // put "15:17" between 12:31 and 13:03 — and printed 15:17 a SECOND time
      // four rows later, for an unrelated report that really was at 15:17.
      //
      // So: scheduled-time rows print the instant they are sorted at, marked
      // SCHED so it is not read as an observation. Everything else prints
      // when it happened. `?? event_time` is a floor, not a fallback — no row
      // may print "—" again, and every kind has one or the other.
      const scheduledTime = SCHEDULED_TIME_KINDS.has(r.status_kind);
      const stamp = scheduledTime ? r.event_time : (r.log_time ?? r.event_time);
      const timeStr = TIME_FMT.format(new Date(stamp));

      // QUALIFIER. The badge is a short form and for four kinds it drops the
      // only fact that distinguishes the row:
      //   missed_answered_late  badge says MISSED / ANSWERED LATE and loses
      //                         both WHEN it was answered and by how much
      //   on_time / late        badge says PING / LATE PING and loses how far
      //                         into the window it landed — which is the only
      //                         thing separating two pings in the same minute
      //                         that answered DIFFERENT windows
      //   clocked_in_late       builder sets status 'Clocked In' for BOTH
      //                         clock-in kinds, so the delta has to be
      //                         computed, exactly as ActivityLogTable does it
      const qualifier = buildQualifier(r, STATUS_LABEL[r.status_kind]);
      const detail    = r.description ?? qualifier;
      const rowHeight = detail ? ROW_DESC_H : ROW_H;
      ensureRoom(rowHeight + 4);

      // No `?? MUTED` / `?? r.status.toUpperCase()` any more. Both maps are
      // Record<StatusKind, ...>, so a fallback here could only ever hide the
      // next missing key the way it hid the last four.
      const color = STATUS_COLOR[r.status_kind];
      const label = STATUS_LABEL[r.status_kind];

      doc.fontSize(8).fillColor(MUTED).font('Helvetica')
         .text(timeStr, COL_TIME_X, y + 3, { lineBreak: false, width: 50 });
      if (scheduledTime) {
        doc.fontSize(6).fillColor(MUTED).font('Helvetica')
           .text('SCHED', COL_TIME_X, y + 11, { lineBreak: false, width: 50 });
      }
      badge(doc, COL_STATUS_X, y + 1, label, color);
      doc.fontSize(8).fillColor(TEXT).font('Helvetica')
         .text(r.guard_name, COL_GUARD_X, y + 3, { lineBreak: false, width: 120 });
      doc.fontSize(8).fillColor(MUTED).font('Helvetica')
         .text(r.site_name, COL_SITE_X, y + 3, { lineBreak: false, width: 200 });

      if (detail) {
        const snippet = detail.length > 180 ? detail.slice(0, 180) + '…' : detail;
        doc.fontSize(8).fillColor('#374151').font('Helvetica')
           .text(snippet, COL_DESC_X, y + 15, { width: CW - 16, height: 10 });
      }

      const mediaCount = r.log_media_urls?.length ?? 0;
      if (mediaCount > 0) {
        doc.fontSize(7).fillColor(MUTED).font('Helvetica')
           .text(`${mediaCount} photo${mediaCount === 1 ? '' : 's'}`,
                 0, y + 3, { align: 'right', width: PAGE_W - ML - 10 });
      }

      y += rowHeight;
      doc.moveTo(ML, y).lineTo(MR, y).strokeColor(GRAY2).lineWidth(0.3).stroke();
      y += 2;
    }
    y += 8;
  }

  // ── Chrome last, now that the page count is known ─────────────────────
  stampPages(doc, 'ACTIVITY LOGS', (d) => drawFooter(d, siteLabel, periodStr));
  doc.end();

  return done;
}
